apps/rrhh/urls.py
from django.urls import path
from apps.rrhh.viewstotal import persona, periodo_trabajo

urlpatterns = [
    # PERSONA
    path('', persona.HomeView.as_view(), name='persona'),
    path('crear/', persona.CrearPersonaView.as_view(), name='persona-crear'),
    path('editar/<int:pk>/', persona.EditarPersonaView.as_view(), name='persona-editar'),
    path('eliminar/<int:pk>/', persona.EliminarPersonaView.as_view(), name='persona-eliminar'),

    # PERIODO TRABAJO
    path('periodo_trabajo/<int:pk>/', periodo_trabajo.HomeView.as_view(), name='periodo_trabajo'),
    path('periodo_trabajo/crear/<int:persona>/', periodo_trabajo.CrearPeriodoTrabajoView.as_view(), name='periodo_trabajo-crear'),
    path('periodo_trabajo/editar/<int:pk>/', periodo_trabajo.EditarPeriodoTrabajoView.as_view(),
         name='periodo_trabajo-editar'),
    path('periodo_trabajo/eliminar/<int:pk>/', periodo_trabajo.EliminarPeriodoTrabajoView.as_view(),
         name='periodo_trabajo-eliminar'),

]

prueba/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('persona/', include('apps.rrhh.urls')),
]

apps/rrhh/models.py
from django.db import models


# Create your models here.


class Persona(models.Model):
    nombres = models.CharField(max_length=100)
    dni = models.CharField(max_length=8)
    nacimiento = models.DateField()

    def __str__(self):
        return f"{self.nombres}"


class PeriodoTrabajo(models.Model):
    persona = models.ForeignKey(Persona, on_delete=models.PROTECT)
    inicio = models.DateField()
    fin = models.DateField(blank=True, null=True)
    cargo = models.CharField(max_length=150)
    area = models.CharField(max_length=150)

    def __str__(self):
        return f"{self.persona.nombres} - {self.cargo}"

apps/rrhh/templates/rrhh/periodo_trabajo/form_eliminar.html
Deseas Eliminar a:
<p class="alert alert-info">
    {{ object }}
</p>

apps/rrhh/templates/rrhh/periodo_trabajo/formulario.html
{{ form.as_p }}

apps/rrhh/templates/rrhh/periodo_trabajo/home.html
{% extends 'base/base.html' %}
{% block titulo %}
    Persona
{% endblock %}
{% block cuerpo_master %}
    <h1>PERIODO TRABAJO</h1>
    <hr>
    <p class="display">
        NOMBRE: <strong>{{ object.nombres }}</strong>
    </p>
    <p class="display">
        DNI: <strong>{{ object.dni }}</strong>
    </p>
    <p class="display">
        FECHA: <strong>{{ object.nacimiento }}</strong>
    </p>
    <a class="btn btn-warning btn-sm" href="{% url 'persona' %}">Atras</a>
    <hr>
    <button id="btnNuevoPeriodoTrabajo" type="button" class="btn btn-primary btn-sm m-2">Nueva Persona</button>
    <br>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>FECHA INICIO</th>
            <th>FECHA FIN</th>
            <th>AREA</th>
            <th>Acciones</th>
        </tr>
        </thead>
        <tbody>
        {% for periodotrabajo in object.periodotrabajo_set.all %}
            <tr>
                <td>{{ periodotrabajo.inicio }}</td>
                <td>{{ periodotrabajo.fin }}</td>
                <td>{{ periodotrabajo.area }}</td>
                <td>
                    <div class="btn-group">
                        <button class="btn btn-info btn-sm btnEditar" data-pk="{{ periodotrabajo.id }}">Editar</button>
                        <button class="btn btn-danger btn-sm btnEliminar" data-pk="{{ periodotrabajo.id }}">Eliminar
                        </button>
                    </div>
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock %}
{% block scripts_master %}
    <script>
        const modal = $("#modalGeneral");
        const btnNuevoPeriodoTrabajo = document.getElementById("btnNuevoPeriodoTrabajo");
        const fomulario_modal = document.getElementById("formModal");
        const btnEditar = document.querySelectorAll('.btnEditar');
        const btnEliminar = document.querySelectorAll('.btnEliminar');
        let url = "";
        btnNuevoPeriodoTrabajo.onclick = () => {
            url = "{% url 'periodo_trabajo-crear' object.pk %}";
            let datos = {
                url: url,
                titulo: "Nueva Periodo trabajo"
            }
            openModal(modal, fomulario_modal, datos);
        }
        btnEditar.forEach(element => {
            element.addEventListener("click", evt => {
                url = "{% url 'periodo_trabajo-editar' 0 %}".replace("/0", "/" + element.dataset.pk);
                let datos = {
                    url: url,
                    titulo: "Editar Persona"
                }
                openModal(modal, fomulario_modal, datos);
            });
        });
        btnEliminar.forEach(element => {
            element.addEventListener("click", evt => {
                url = "{% url 'periodo_trabajo-eliminar' 0 %}".replace("/0", "/" + element.dataset.pk);
                let datos = {
                    url: url,
                    titulo: "Eliminar Persona"
                }
                openModal(modal, fomulario_modal, datos);
            });
        });
        fomulario_modal.onsubmit = async (ev) => {
            submitForm(ev, url, fomulario_modal, () => {
                location.reload();
            })
        }
    </script>
{% endblock %}

apps/rrhh/templates/rrhh/persona/form_persona.html
{{ form.as_p }}

apps/rrhh/templates/rrhh/persona/form_persona_eliminar.html
Deseas Eliminar a:
<p class="alert alert-info">
    {{ object }}
</p>

apps/rrhh/templates/rrhh/persona/home.html
{% extends 'base/base.html' %}
{% block titulo %}
    Persona
{% endblock %}
{% block cuerpo_master %}
    <h1>PERSONA</h1>
    <hr>
    <button id="btnNuevaPersona" type="button" class="btn btn-primary btn-sm m-2">Nueva Persona</button>
    <br>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Nombres</th>
            <th>DNI</th>
            <th>Fecha Nacimiento</th>
            <th>Acciones</th>
        </tr>
        </thead>
        <tbody>
        {% for persona in persona %}
            <tr>
                <td>{{ persona.nombres }}</td>
                <td>{{ persona.dni }}</td>
                <td>{{ persona.nacimiento }}</td>
                <td>
                    <div class="btn-group">
                        <button class="btn btn-info btn-sm btnEditar" data-pk="{{ persona.id }}">Editar</button>
                        <button class="btn btn-danger btn-sm btnEliminar" data-pk="{{ persona.id }}">Eliminar</button>
                        <a class="btn btn-secondary btn-sm" href="{% url 'periodo_trabajo' persona.id %}">Historial</a>
                    </div>
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock %}
{% block scripts_master %}
    <script>
        const modal = $("#modalGeneral");
        const btnNuevaPersona = document.getElementById("btnNuevaPersona");
        const fomulario_modal = document.getElementById("formModal");
        const btnEditar = document.querySelectorAll('.btnEditar');
        const btnEliminar = document.querySelectorAll('.btnEliminar');
        let url = "";
        btnNuevaPersona.onclick = () => {
            url = "{% url 'persona-crear' %}";
            let datos = {
                url: "{% url 'persona-crear' %}",
                titulo: "Nueva Persona"
            }
            openModal(modal, fomulario_modal, datos);
        }
        btnEditar.forEach(element => {
            element.addEventListener("click", evt => {
                url = "{% url 'persona-editar' 0 %}".replace("/0", "/" + element.dataset.pk);
                let datos = {
                    url: url,
                    titulo: "Editar Persona"
                }
                openModal(modal, fomulario_modal, datos);
            });
        });
        btnEliminar.forEach(element => {
            element.addEventListener("click", evt => {
                url = "{% url 'persona-eliminar' 0 %}".replace("/0", "/" + element.dataset.pk);
                let datos = {
                    url: url,
                    titulo: "Eliminar Persona"
                }
                openModal(modal, fomulario_modal, datos);
            });
        });
        fomulario_modal.onsubmit = async (ev) => {
            submitForm(ev, url, fomulario_modal, () => {
                location.reload();
            })
        }
    </script>
{% endblock %}

templates/base/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    {% block style_master %}

    {% endblock %}
    <title>{% block titulo %}

    {% endblock %}</title>
</head>
<body>
<div class="container">
    {% block cuerpo_master %}

    {% endblock %}

    <form id="formModal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div id="modalGeneral" class="modal fade" tabindex="-1" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        ...
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
{#<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"#}
{#        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"#}
{#        crossorigin="anonymous"></script>#}
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
-->

<script>
    function openModal(modal, formulario, datos) {
        modal.find(".modal-title").text(datos.titulo);
        $(".modal-body").load(datos.url);
        formulario.setAttribute("acction", datos.url);
        modal.modal("show");
    }

    async function submitForm(ev, url = '', fomulario, funcion) {
        ev.preventDefault();
        let formdata = new FormData(fomulario);
        let response = await fetch(url, {
            method: 'POST',
            body: formdata
        }).then(datos => datos);
        if (response.ok) {
            funcion();
        }
    }

    {#async function postData(url = '', data = {}) {#}
    {#    // Opciones por defecto estan marcadas con un *#}
    {#    const response = await fetch(url, {#}
    {#        method: 'POST', // *GET, POST, PUT, DELETE, etc.#}
    {#        mode: 'cors', // no-cors, *cors, same-origin#}
    {#        cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached#}
    {#        credentials: 'same-origin', // include, *same-origin, omit#}
    {#        headers: {#}
    {#            'Content-Type': 'application/json'#}
    {#            // 'Content-Type': 'application/x-www-form-urlencoded',#}
    {#        },#}
    {#        redirect: 'follow', // manual, *follow, error#}
    {#        referrerPolicy: 'no-referrer', // no-referrer, *no-referrer-when-downgrade, origin, origin-when-cross-origin, same-origin, strict-origin, strict-origin-when-cross-origin, unsafe-url#}
    {#        body: formData // body data type must match "Content-Type" header#}
    {#    });#}
    {#    return response.json(); // parses JSON response into native JavaScript objects#}
    {# }#}
</script>


{% block scripts_master %}

{% endblock %}
</body>
</html>